### ISSUE TITLE
Collection doesn't contain element at index 19.

### ISSUE THREAD

**Issue by aisbergde** [aivanovski/kpassnotes#177] opened 2023-08-27 06:29 UTC
When I try to open an existing keepass file (my main file), then I get the error

Collection doesn't contain element at index 19.

I have no idea about the reason or meaning. The same file works fine in other keepass clients.

**Comment by aivanovski** [comment] 2023-08-27 12:02
@aisbergde I don't think it could be fixed without at least one of these:
- steps to reproduce
- database file itself
- logs with stacktrace or stacktrace itself.
Could you please provide something?

Here is the instruction on how to share the log file:
- enable the option in settings "Write log to file"
- restart the app
- reproduce the issue (after that log file should have error stacktrace)
- click "Send log file" in settings

**Comment by aivanovski** [comment] 2023-09-08 12:45
Hi @aisbergde
Could you please provide some additional information regarding your issue? Logs or KeePass file for example, pleasae check my previos comment.

**Comment by aisbergde** [comment] 2023-09-09 21:20
I can send the log, but I don't want to send the keepass file. The error happens after password input and I will not provide the password. I don't know how you could debug.

**Comment by aivanovski** [comment] 2023-09-10 06:50
@aisbergde Thank you for your help. I've created [issue](https://github.com/keemobile/kotpass/issues/8) to fix this crash.

According to stack track, kotpass crashes because can't deserialize binary file (attachment) inside some entry.  So, I suppose the reason for the crash is enty with 19 or so attachments. Removing it may eliminate the crash.

**Comment by aisbergde** [comment] 2023-09-10 15:44
I would try to remove them. But therefore I need a way to identify entries containing attached files.

**Closed** 2023-09-14 20:38 UTC

**Comment by aivanovski** [comment] 2023-09-14 20:44
This issue should be fixed in next version v1.1.0
