### ISSUE TITLE
Creating or editing an item crashes GNOME Secrets

### ISSUE THREAD

**Issue by julianfairfax** [aivanovski/kpassnotes#132] opened 2023-05-24 19:36 UTC
I'm not sure what's going on here, but, creating or editing an item with KPassNotes will crash [GNOME Secrets](https://apps.gnome.org/en-GB/app/org.gnome.World.Secrets/) when trying to view it. This is obviously not ideal. The reverse is not an issue.

**Comment by aivanovski** [comment] 2023-05-25 08:32
I've tried to modify some of my test KeePass files with KPassNotes and then open them with GNOME Secrets. No crash has occurred in my case. I think in order to fix this issue we need to find a reliable way to reproduce it.

Probably your file contains some data, that causes a crash. But it would be impossible to just guess the reason.

Could you provide more information about this issue? By that I mean logs, maybe steps to reproduce with completely new file or anything else that may help
@julianfairfax

**Comment by aivanovski** [comment] 2023-05-25 10:38
Was able to reproduce the crash, need some to analyze it.

**Comment by aivanovski** [comment] 2023-06-03 09:54
The reason why GNOME Secrets crashes is the expiration time is not set. If expiration time will be present, then everything will be okay.

I will investigate a little bit more what is right according to KeePass standards. But in general it looks like a bug in GNOME Secrets, the application should not crash if something is missing. It should show an error.

@julianfairfax I would suggest reporting this issue to GNOME Secrets. I actually can make a quick fix for this bug in KPassNotes, but I'm not sure that it is right to write expiration time always even if the user doesn't specify it. Also, you may try KeePassXC instead of GNOME Secrets, it works fine.

Here is a stacktrace from GNOME Secrets:
```
(secrets:99359): IBUS-WARNING **: 11:28:08.708: Unable to connect to ibus: Could not connect: Connection refused

(secrets:99359): Gtk-WARNING **: 11:28:10.696: GtkText - did not receive a focus-out event.
If you handle this event, you must return
GDK_EVENT_PROPAGATE so the default handler
gets the event as well
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/gi/_propertyhelper.py", line 401, in obj_set_property
    prop.fset(self, value)
  File "/usr/lib/python3.11/site-packages/gsecrets/widgets/expiration_date_row.py", line 50, in safe_entry
    expiry_date = entry.expiry_time  # UTC
                  ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/gsecrets/safe_element.py", line 900, in expiry_time
    time = self.entry.expiry_time
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pykeepass/baseelement.py", line 130, in expiry_time
    return self._get_times_property('ExpiryTime')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pykeepass/baseelement.py", line 97, in _get_times_property
    return self._kp._decode_time(prop.text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pykeepass/pykeepass.py", line 897, in _decode_time
    return parser.parse(
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dateutil/parser/_parser.py", line 1368, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dateutil/parser/_parser.py", line 640, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dateutil/parser/_parser.py", line 719, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dateutil/parser/_parser.py", line 201, in split
    return list(cls(s))
                ^^^^^^
  File "/usr/lib/python3.11/site-packages/dateutil/parser/_parser.py", line 69, in __init__
    raise TypeError('Parser must be a string or character stream, not '
TypeError: Parser must be a string or character stream, not NoneType
```

**Closed as completed** 2023-07-03 09:49 UTC
