### ISSUE TITLE
Unable to connect to Git: Network error

### ISSUE THREAD

**Issue by jorisvandijk** [aivanovski/kpassnotes#108] opened 2022-10-29 12:30 UTC
![Screenshot_20221029-142527](https://user-images.githubusercontent.com/2847976/198831563-c7c5b9f8-181c-4051-84b3-555cb528ebb1.png)
When trying to add a got URL, the app will always claim there's a network issue, though I have one. See screenshot.

**Comment by aivanovski** [comment] 2022-10-29 13:33
Application doesn't support SSH protocol now, you should provide HTTPS link to it. This is possible for Gitlab.

**Comment by jorisvandijk** [comment] 2022-10-29 13:43
Thank you for your reply. I also tried https, but this yielded the same error. I used the link as gitlab provided it.

**Comment by jorisvandijk** [comment] 2022-10-29 13:47
Ah, I have just found where the issue may lie. The repository I tried to use is a private one. A public.one it did accept, but I am not willing to store my database in a public repo. Is it possible to add this functionality to your app?

Thank you

**Comment by aivanovski** [comment] 2022-10-29 13:53
If you are using GitLab, then you can generate AccessToken put it inside url to your repository and then your will have read/write access to it. Without AccessToken access will be read-only. Url should look like this: `https://oauth2:YOUR_ACCESS_TOKEN@gitlab.com/USERNAME/REPOSITORY.git`

I will add SSH support to the backlog, but I don't know when I will be able to add it.

**Comment by jorisvandijk** [comment] 2022-10-29 15:11
I might be stupid, but I cannot seem to get it to work.

`https://oauth2:YOUR_ACCESS_TOKEN@gitlab.com/USERNAME/REPOSITORY.git`

Say my username is Jim, my token is 123 and my repo name is repo, would the following be right?

`https://oauth2:123@gitlab.com/jim/repo.git`

**Comment by aivanovski** [comment] 2022-10-29 15:32
Well, check read/write access to your repo via AccessToken from your PC. If it doesn't work, then you should go to the Gitlab documentation and fix it somehow.
If it works on your PC and doesn't work on KPassNotes, then the problem is in KPassNotes.

**Comment by jorisvandijk** [comment] 2022-10-29 15:40
So it only works if I am already logged in to the account when I do it over the browser using the same link. Seems I need to figure out how to pass both username, password and token over a url. Will continue to search for a solution. Thanks again for helping!

**Comment by aivanovski** [comment] 2022-11-05 12:04
Closing it, I assume it was configuration issue, otherwise can reopen it.

**Closed by aivanovski** 2022-11-05 12:04 UTC
