### ISSUE TITLE
Invalid entry field without id

### ISSUE THREAD

**Issue by Bendejo21** [aivanovski/kpassnotes#195] opened 2023-09-30 20:53 UTC
Hallo,

when trying to unlock my kdbx file there is no access: Message "Invalid entry field without id".

Thanks.

**Comment by Bendejo21** [comment] 2023-10-01 11:35
`KotpassDatabase$Companion(17) : app.keemobile.kotpass.errors.FormatError$InvalidXml: Invalid entry field without id.
	at app.keemobile.kotpass.xml.EntryKt.unmarshalField(Entry.kt:105)
	at app.keemobile.kotpass.xml.EntryKt.access$unmarshalField(Entry.kt:1)
	at app.keemobile.kotpass.xml.EntryKt.unmarshalEntry(Entry.kt:61)
	at app.keemobile.kotpass.xml.GroupKt.unmarshalGroup(Group.kt:78)
	at app.keemobile.kotpass.xml.DefaultXmlContentParser.unmarshalContent(DefaultXmlContentParser.kt:38)
	at app.keemobile.kotpass.database.DecoderKt.decode(Decoder.kt:96)
	at app.keemobile.kotpass.database.DecoderKt.decode$default(Decoder.kt:25)
	at com.ivanovsky.passnotes.data.repository.keepass.kotpass.KotpassDatabase$Companion.open(KotpassDatabase.kt:464)
	at com.ivanovsky.passnotes.data.repository.keepass.KeepassDatabaseRepository.openDatabase(KeepassDatabaseRepository.kt:196)
	at com.ivanovsky.passnotes.data.repository.keepass.KeepassDatabaseRepository.open(KeepassDatabaseRepository.kt:61)
	at com.ivanovsky.passnotes.domain.interactor.unlock.UnlockInteractor$openDatabase$2.invokeSuspend(UnlockInteractor.kt:111)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)`

**Comment by aivanovski** [comment] 2023-10-01 11:42
Hi, @Bendejo21
Thank you for the report! This issue is caused by the [kotpass](https://github.com/keemobile/kotpass) library responsible for file decoding. Could you please create an issue there? After it will be fixed, I can update the version of this library and I hope everything will be OK.

**Comment by Bendejo21** [comment] 2023-10-01 12:11
> Hi, @Bendejo21 Thank you for the report! This issue is caused by the [kotpass](https://github.com/keemobile/kotpass) library responsible for file decoding. Could you please create an issue there? After it will be fixed, I can update the version of this library and I hope everything will be OK.

Thanks. Done.
[Issue](https://github.com/keemobile/kotpass/issues/10#issue-1920734022)

**Closed** 2023-10-11 11:56 UTC
